"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let countriesTovisit = ["china", "denmark", "brazil", "argentina"];
console.log("original order:", countriesTovisit);
console.log("Alphabetical Order:", [...countriesTovisit].sort());
console.log("still in original order:", countriesTovisit);
console.log("Reverse Order:", [...countriesTovisit].reverse());
console.log("still in original Order:", countriesTovisit);
console.log("original array reverse:", countriesTovisit.reverse());
console.log("back to oriinal order:", countriesTovisit.reverse());
console.log("sorted in alphabetical order:", countriesTovisit.sort());
console.log("original array reverse:", countriesTovisit.reverse());
